USE MyDatabase;
GO

-- 1. READ UNCOMMITTED (Незавершенное чтение):


SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;
	SELECT * FROM Auto;
	WAITFOR DELAY '00:00:05';
	SELECT * FROM Auto;
COMMIT TRANSACTION;
GO


-- 2. READ COMMITTED (Завершенное чтение):

/*
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
    SELECT * FROM Auto;	
	WAITFOR DELAY '00:00:05';
	SELECT * FROM Auto;
COMMIT TRANSACTION;
GO
*/

--3. REPEATABLE READ (Воспроизводимое чтение):

/*
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION;
    SELECT * FROM Auto;	
	WAITFOR DELAY '00:00:05';
	SELECT * FROM Auto;
COMMIT TRANSACTION;
GO
*/

--4. SERIALIZABLE (Сериализуемое выполнение):

/*
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION;
	SELECT * FROM Auto;	
	WAITFOR DELAY '00:00:05';
	SELECT * FROM Auto;
COMMIT TRANSACTION;
GO*/